apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-echo-server-gitee
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters: {}
#        selector:
#          matchExpressions:
#            - key: argocd.argoproj.io/secret-type
#              operator: In
#              values:
#                - cluster
#            - key: cluster_name
#              operator: NotIn
#              values:
#                - in-cluster
#          matchLabels:
#            argocd.argoproj.io/secret-type: cluster
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{.metadata.annotations.cluster_name}}-echoserver'
      namespace: argocd
    spec:
      project: "default"
      source:
        helm:
          parameters:
            - name: replicaCount
              value: "2"
          valueFiles:
            - values.yaml
        repoURL: https://github.com/AliyunContainerService/gitops-demo.git
        targetRevision: main
        path: manifests/helm/echo-server
      destination:
        server: '{{.server}}'
        namespace: demo
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true